[[constraint]]
  branch = "release-1.16"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "0.16.8"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "k8s.io/klog"
  version = "0.4.0"
