apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clear-impaired-volumes-taint
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clear-impaired-volumes-taint
subjects:
- kind: ServiceAccount
  name: clear-impaired-volumes-taint
  namespace: ops